
import { Product } from '@/types';
import { ProductStatus, ProductUnit } from '@/constants/inventory';

export const products: Product[] = [
  {
    id: '1',
    name: 'أرز بسمتي',
    category: 'بقالة',
    unit: 'kg' as ProductUnit,
    quantity: 50,
    expiryDate: new Date('2024-06-30'),
    entryDate: new Date('2023-06-15'),
    restaurantId: '1',
    restaurantName: 'مطعم البيت الدمشقي',
    addedBy: 'محمد الحسن',
    status: ProductStatus.ACTIVE,
  },
  {
    id: '2',
    name: 'دجاج مجمد',
    category: 'لحوم',
    unit: 'kg' as ProductUnit,
    quantity: 30,
    expiryDate: new Date('2024-01-30'),
    entryDate: new Date('2023-07-01'),
    restaurantId: '1',
    restaurantName: 'مطعم البيت الدمشقي',
    addedBy: 'عمر محمود',
    status: ProductStatus.ACTIVE,
  },
  {
    id: '3',
    name: 'زيت زيتون',
    category: 'زيوت',
    unit: 'l' as ProductUnit,
    quantity: 20,
    expiryDate: new Date('2024-12-25'),
    entryDate: new Date('2023-06-20'),
    restaurantId: '2',
    restaurantName: 'مطعم أرابيسك',
    addedBy: 'سارة أحمد',
    status: ProductStatus.ACTIVE,
  },
  {
    id: '4',
    name: 'طماطم',
    category: 'خضروات',
    unit: 'kg' as ProductUnit,
    quantity: 15,
    expiryDate: new Date('2023-07-25'),
    entryDate: new Date('2023-07-10'),
    restaurantId: '1',
    restaurantName: 'مطعم البيت الدمشقي',
    addedBy: 'محمد الحسن',
    status: ProductStatus.EXPIRED,
  },
];
